
language: java
jdk:
  - openjdk17

branches:
  only:
    - main

env:
  global:
    - EMAIL_USERNAME: $EMAIL_USERNAME
    - EMAIL_PASSWORD: $EMAIL_PASSWORD

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/galendar-server.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: galendar-server-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: galendar-server-build
    key: galendar-server.zip
    bundle_type: zip
    application: galendar-server
    deployment_group: galendar-server-group
    region: ap-northeast-2
    on:
      all_branches: true

notifications:
  email:
    recipients:
      - kimwongi@kakao.com
